In [2]:
import numpy as np

In [6]:
benimDizim = np.arange(0,15)

In [7]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
benimDizim[5]

5

In [10]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [16]:
benimDizim[3:8] = -5

In [17]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [18]:
baskaDizi = np.arange(0,24)

In [19]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [27]:
slicingDizisi = baskaDizi[4:9]

In [28]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [29]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [33]:
slicingDizisi[:] = 700 # içerisindeki tüm elemanları almak için : kullanılır.

In [34]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [35]:
baskaDizi # slicing dizisini değiştirdiğimiz halde, numpy dizimizin içerisindeki elemanlarda değişti. Bir dizi
#içerisinden başka bir dizi çekip o dizi üzerinde değişiklik yaptığımız halde, ana dizi üzerinde değişiklikler
#kaydedildi. Orjinalini etkilemesin diyorsak aşağıdaki işlemler uygulanır.

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [36]:
ornekDizi = np.arange(0,24)

In [37]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [40]:
ornekDiziKopyasi = ornekDizi.copy() # kopyasını oluşturmamız lazım 

In [41]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [42]:
ornekDiziKopyaSlicing = ornekDiziKopyasi [3:6]

In [44]:

ornekDiziKopyaSlicing[:] = 800

In [45]:
ornekDiziKopyaSlicing

array([800, 800, 800])

In [46]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [49]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [51]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [55]:
benimMatrixDizim = np.array(benimListem)

In [56]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [57]:
benimMatrixDizim[0]

array([10, 20, 30])

In [58]:
benimMatrixDizim[1][2] # birinci row ikinci column

40

In [69]:
benimMatrixDizim[1,2]

40

In [63]:
benimMatrixDizim[1:,2]  #birinci rowdan başla ve ikinci indexleri getir demek oluyor.

array([40, 60])

In [71]:
benimMatrixDizim[0:1,1:2]

array([[20]])

In [73]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[16,16,17,18,19],[20,21,22,23,24]]

In [74]:
yeniMatrix = np.array(yeniListe)

In [75]:
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [16, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [76]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [78]:
yeniMatrix[[0,2,4]] # istediğimiz indexlerdeki rowları getirdi.Sıra önemli değil.
                    #İndex yerine liste veriyoruz, ayrı bir dizi döndürüyor.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operasyonlar

In [82]:
yeniBirDizi = np.random.randint(1,100,20)

In [83]:
yeniBirDizi

array([17, 80,  2, 32, 88, 92, 68, 38, 38, 69, 22, 77,  8, 74, 25, 21, 73,
       71, 33, 92])

In [85]:
yeniBirDizi > 24 #24 ten büyük elemanları tek tek boolean olarak bize tekrar döndürüyor.

array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False,  True,  True,
        True,  True])

In [86]:
yeniBirDizi

array([17, 80,  2, 32, 88, 92, 68, 38, 38, 69, 22, 77,  8, 74, 25, 21, 73,
       71, 33, 92])

In [87]:
sonucDizisi = yeniBirDizi > 24

In [88]:
sonucDizisi

array([False,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False,  True,  True,
        True,  True])

In [89]:
yeniBirDizi


array([17, 80,  2, 32, 88, 92, 68, 38, 38, 69, 22, 77,  8, 74, 25, 21, 73,
       71, 33, 92])

In [92]:
yeniBirDizi[sonucDizisi] #Sonuc dizisindeki false değerleri almayıp sadece true olanları filtreleyen mükemmel özellik. 

array([80, 32, 88, 92, 68, 38, 38, 69, 77, 74, 25, 73, 71, 33, 92])

In [93]:
yeniBirDizi

array([17, 80,  2, 32, 88, 92, 68, 38, 38, 69, 22, 77,  8, 74, 25, 21, 73,
       71, 33, 92])

In [94]:
yeniBirDizi[yeniBirDizi < 24] # tek bir satırda da aynı işlem yapılabilir.

array([17,  2, 22,  8, 21])

In [97]:
sonDizi = np.arange(0,24)

In [98]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [100]:
sonDizi + sonDizi  #her indexi kendi indexleriyle toplar.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [101]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [102]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [103]:
sonDizi-sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [106]:
sonDizi/sonDizi

<ipython-input-106-7d5697280f2b>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi/sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [108]:
np.sqrt(sonDizi) #Karekök alma

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [109]:
np.max(sonDizi)

23

In [110]:
np.min(sonDizi)

0