In [6]:
import numpy as np

## Numpy

Temel dizi vs oluşturmalarını sağlayan kütüphane. Çok fazla kullanılan bir kütüphanedir.

## Numpy Array

In [7]:
#tek boyutlu ya da iki boyutlu diziler oluşturabiliyoruz.

benimListem = [20,30,40]

In [8]:
type(benimListem)

list

In [11]:
np.array(benimListem) # numpy listesine convert

array([20, 30, 40])

In [12]:
#Dizi içerisinde dizi oluşturabiliriz.

matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [13]:
type(matrixListesi)

list

In [16]:
np.array(matrixListesi) #aslında farklı bir şey değil ama matrix olarak gözükmesini sağladı.

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arenge

In [17]:
list(range(0,10))#liste oluşturma

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,10,2) #step-size vererk oluşturma #staringIndex,stoppinIndex,Step-sizeIndex

array([0, 2, 4, 6, 8])

## Zeros

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Linspace

In [28]:
                    #0 la 20 arasında 5 tane rakam seç araları eşit olsun.
np.linspace(0,20,6)#belirriğimiz numaralar arasında eşit olarak boyutlandırılmış (aralık bırakılmıl) bir dizi oluşturur.

array([ 0.,  4.,  8., 12., 16., 20.])

In [29]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## eye

In [35]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## random 

In [45]:
np.random.randn(4,4)

array([[-0.73403613,  0.12987467, -1.368607  , -0.51145943],
       [ 1.62540804, -0.23835746,  1.25658897,  1.87151792],
       [-0.65701136, -0.65585316, -0.80583164, -0.73365016],
       [ 1.59020585,  0.95321266, -0.30567158,  1.02640714]])

In [111]:
np.random.randint(1,10) #aralıkta random sayı oluşturur.

1

In [112]:
np.random.randint(1,300,5) # aralıkta 5 tane random sayı oluşturur.

array([142, 260, 102, 102,  59])

In [113]:
benimNumpyDizim = np.arange(30)  #oluşturulan sayılar bir diziye aktarılabilir.

In [114]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [118]:
benimRandomDizim = np.random.randint(0,100,20) #random oluşturulan sayılar bir diziye aktarılabilir.

In [119]:
benimRandomDizim

array([70, 49,  6,  2, 78, 13, 40, 81,  2, 29, 48,  4, 87, 77, 73, 22, 70,
       35, 31, 72])

## Numpy Dizi Methodları

In [126]:
benimNumpyDizim.reshape(5,6) #tekrar şekillendir methodu

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [127]:
benimNumpyDizim.max()

29

In [129]:

benimRandomDizim.max()

87

In [130]:
benimRandomDizim.min()

2

In [131]:
benimRandomDizim.argmax()

12

In [132]:
benimRandomDizim.argmin()

3

In [136]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [137]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [138]:
reshapeDizim.shape #güncel dizimin hangi şekle sahip olduğunu bu şekilde alabiliyorum.

(5, 6)